### ISSUE TITLE
[openapi-gen][bug][java-client] Nullable field failing when explicitly set to "null"

### ISSUE THREAD

**Issue by VamshikShetty** [equinix-labs/metal-java#15]
Recently openapi generator fixed bug in java pojo template : https://github.com/OpenAPITools/openapi-generator/issues/12549
This fix is not available in any stable version hence we have to move to latest image until a new stable version is released.

**Comment by displague** [comment]
An alternative would be to patch the OAS3 (3.0) spec to indicate that these fields are `nullable: true`, although I don't know if the issue referred to in the issue description handles that scenario any better.

**Comment by VamshikShetty** [comment]
So before fix mentioned in https://github.com/OpenAPITools/openapi-generator/issues/12549 following is code pattern that would be generated.

```
if ((jsonObj.get("description") != null && !jsonObj.get("description").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `description` to be a primitive type in the JSON string but got `%s`", jsonObj.get("description").toString()));
      }
```

Here variable jsonObj is of type gson.JsonObject which returns JsonNull.Instance instead of null when its corresponding parameter is null. Now `JsonNull.Instance` is not equal to null and if its a primitive type then exception inside if block is thrown.

Correct flavour would be to check if returned value is not JsonNull, which is the produced code after the fix went in :
```
if ((jsonObj.get("description") != null && !jsonObj.get("description").isJsonNull()) && !jsonObj.get("description").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `description` to be a primitive type in the JSON string but got `%s`", jsonObj.get("description").toString()));
      }
```
