### ISSUE TITLE
Create patches for Otps tag

### ISSUE THREAD

**Issue by displague** [equinix-labs/metal-java#4]
The `OTPs` spec tag is typo'd in one location as `Otps`. This causes problems with the code generation. Standardize the references to this tag in the spec via patches.

For example: https://github.com/equinix-labs/metal-go/blob/main/patches/spec.fetched.json/01_otps.patch

**Comment by VamshikShetty** [comment]
Patch addressing spec inconsistency w.r.t otps tag : https://github.com/equinix-labs/metal-java/blob/main/patches/spec.fetched.json/01-otps-case-correction.patch
