### ISSUE TITLE
CI Sync fails when there are no incoming API spec changes

### ISSUE THREAD

**Issue by displague** [equinix-labs/metal-java#94]
It is misleading to see a failed [`Sync` job](https://github.com/equinix-labs/metal-java/blob/main/.github/workflows/sync.yml) when there are no upstream API changes. Arguably, sync should be successful in that condition -- "✅ we are in sync".

https://github.com/equinix-labs/metal-java/actions/runs/5013948490

```
$ make fetch
docker  run --rm -u 1001:123 -v /home/runner/work/metal-java/metal-java:/workdir --entrypoint sh mikefarah/yq:4.30.8 script/download_spec.sh https://api.equinix.com/metal/v1/api-docs spec/oas3.fetched//openapi/public openapi3.yaml
...
saving to 'spec/oas3.fetched//openapi/public/paths/vrfs/id/routes.yaml'
routes.yaml          100% |********************************|  2367  0:00:00 ETA
'spec/oas3.fetched//openapi/public/paths/vrfs/id/routes.yaml' saved
On branch main
Your branch is up to date with 'origin/main'.

nothing to commit, working tree clean
```
(exits with non zero code)

**Comment by ctreatma** [comment]
Closed by #105 which removes a few failure modes from the sync job:
- no longer fails when spec is already up-to-date
- no longer fails when patching or code generation fails (will open a draft PR with the changes that succeeded, and add a comment about what failed)
